// vue-lesson/vue-vuex-hello/src/components/TodoFooter.vue
<template>
  <div class="todo-footer">
    <span>0 item left</span>
    <div class="btns">
      <button>all</button>
      <button>active</button>
      <button>completed</button>
    </div>
    <button>clear completed</button>
  </div>
</template>

<script>
export default {

}
</script>

<style>
.todo-footer{
  margin-top: 30px;
  display: flex;
}
.todo-footer .btns{
  display: flex;
  margin-left: 20px;
  margin-right: 20px;
}
</style>

// react-lesson/react-redux-tookit/src/components/TodoFooter.js

export default function TodoFooter() {
  return (
    <div style={{marginLeft: '20px'}} className="todo-footer">
      <span>0 items left</span>
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>all</button>  
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>active</button>  
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>completed</button>  
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>delete completed</button>
    </div>
  )
}
