// react-lesson/react-redux-tookit/src/components/TodoFooter.js

export default function TodoFooter() {
  return (
    <div style={{marginLeft: '20px'}} className="todo-footer">
      <span>0 items left</span>
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>all</button>  
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>active</button>  
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>completed</button>  
      <span>&nbsp;&nbsp;&nbsp;</span>
      <button>delete completed</button>
    </div>
  )
}

// vue-lesson/vue-todo/src/components/TodoFooter.vue
<template>
  <div class="todo-footer">
    <span class="left">1 item left</span>
    <div class="btns">
      <button>All</button>
      <button>Active</button>
      <button>Completed</button>
    </div>
    <button class="right">Clear completed</button>
  </div>
</template>

<script>
export default {

}
</script>

<style>
.todo-footer {
  display: flex;
  padding: 20px 0;
  justify-content: space-between;
  align-items: center;
  position: relative;
}
.todo-footer .btns {
  position: absolute;
  top: 50%;
  left: 46%;
  transform: translate(-50%, -50%);
}

</style>
